### ISSUE TITLE
Trying to price a fractured unique ring that has been vaaled into a rare causes a repeated error message and crash.

### ISSUE THREAD

**Issue by levmeister** [Ethck/Path-of-Accounting#110]
Well this is kind of a really niche case... I'm just gonna post the ring I tried to price, there are so many things going on with it I'm not sure what caused the problem: 

Rarity: Rare
Dread Knot
Synthesised Ruby Ring
--------
Requirements:
Level: 48
--------
Item Level: 82
--------
13% reduced Reflected Damage taken (implicit)
20% increased Damage if Corrupted (implicit)
--------
7% increased Cold Damage
Adds 1 to 22 Lightning Damage to Attacks
+293 to Accuracy Rating
+13 to maximum Energy Shield
+65 to maximum Life
+1 Mana gained on Kill
--------
Corrupted
--------
Synthesised Item

**Comment by Ethck** [comment]
With all of the improvements in the dev branch, I thought for sure I'd already had this fixed. It is not. The reason this item is breaking is because it is a synthesized item. PoA tries to read this item's base type as "Synthesized Ruby Ring" and searches for that base on the api. There is no base with that name. I will have a fix out shortly, and it will be in the next pre-release version. Thanks for finding this.
