### ISSUE TITLE
Linux support.

### ISSUE THREAD

**Issue by Qfl3x** [Ethck/Path-of-Accounting#27]
If you can guide me on how to replace the dll's with their respective libraries I'll gladly do it.

**Comment by Ethck** [comment]
So the basis of this is the python script (which is linux compatible) and can be executed with `python3 parse.py` after installing the requests and colorama libraries (`pip3 install requests colorama`); however, there are some bugs with it right now (like a ton of tk() windows popping up). If you can find out how to get that bug fixed, then everything should work fine. Otherwise, I'll have to figure out a different way to access the keyboard in linux.

**Comment by Kyria** [comment]
can you add a "requirements.txt" listing those requirements ? This will help people on unix system and / or people who may want to help dev :)

**Comment by Ethck** [comment]
As far as I can tell, the script works perfectly fine with linux. requirements.txt was just updated into master. Closing.

**Comment by InFerYes** [comment]
@Ethck I'm getting

```
 ~/Games/path-of-accounting % python3 parse.py                                                                                                                                                                                                                                                                                                                            :(
Traceback (most recent call last):
  File "parse.py", line 3, in <module>
    from tkinter import Tk, TclError
  File "/usr/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```

Perhaps the `requirements.txt` file should be updated.

I needed to install tk

`sudo pacman -S tk`

**Comment by Ethck** [comment]
Oops, I totally forgot there were still python versions that did not ship with tk. Will fix in next update.
