### ISSUE TITLE
hotkey.py should be optional

### ISSUE THREAD

**Issue by woefulwabbit** [Ethck/Path-of-Accounting#56]
hotkey.py depends on keyboard module, which requires sudo/root on linux. The module is missing from requirements.txt and the functionality is not necessary to the main purpose of Path of Accounting so should probably be made optional some how.

**Comment by zero-code-hero** [comment]
I opened https://github.com/Ethck/Path-of-Accounting/pull/59 which adds the missing module.

For more advanced QOL features it may be necessary to run as root. But I could see both sides here. @Ethck will be pretty limited if he is only able to read the contents of the clipboard.

**Comment by Ethck** [comment]
@woefulwabbit I am beginning to incorporate a GUI in which many of the features will be accessible via key binds with no permanent presence. I have chosen to use the `keyboard` library because it requires an elevated privilege level (and warns you so) for transparency. Especially with key-logging, I am to maintain complete transparency since it can be dangerous. Are you on an environment in which you do not have privileged access? If so I can find a work around. Otherwise, in an upcoming settings update I will make the use of keybinds optional.

**Comment by Ethck** [comment]
@woefulwabbit dev branch now has the ability to toggle all but the most essential pieces of Path of Accounting.
